# vim: expandtab tabstop=2 
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Weekly
    - cron: '0 0 * * 0'


jobs:
  package:
    name: "Package Ghidra"
    container: python:3.7-alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install CDR kit to create Disk Images
        shell: sh
        run: apk add cdrkit
      - name: Install dependencies
        shell: sh
        run: pip install -r requirements.txt
      - name: Download and package Ghidra
        shell: sh
        run: ./update.py --dmg
      - name: "Upload package"
        uses: actions/upload-artifact@v2
        with:
          path: "*.dmg"

